#!/bin/bash
session=fille

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    # Start session
    sudo -u $session tmux new-session -d -s $session
    # Start weechat
    sudo -u $session tmux new-window 'weechat'
    ;;
  stop)
    sudo -u $session tmux kill-session -t $session
  ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0


